[app]
name = "Wormhole Portal"
version = "1.0.0"
description = "Ledger plugin for the Wormhole Portal Token Bridge"
authors = ["Michael Mann <michaelmann@disroot.org>"]
repository = "https://github.com/bymichaelmann/wormhole-ledger-plugin"
homepage = "https://github.com/bymichaelmann/wormhole-ledger-plugin"
license = "Apache-2.0"
icons = "icons/"

[ethereum]
contract = "0x3ee18b2214aff97000d974cf647e7c347e8fa585"
plugin_name = "Wormhole Portal"
