homepage: "https://github.com/bymichaelmann/wormhole-ledger-plugin"
language: c
primary_contact: "michaelmann@disroot.org"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: "https://github.com/bymichaelmann/wormhole-ledger-plugin"
